// Mock data for the admin dashboard

import {
  Project,
  Course,
  Message,
  MediaItem,
  DashboardStats,
  RecentActivity,
} from '@/types/dashboard';

export const mockStats: DashboardStats = {
  totalProjects: 24,
  newMessages: 8,
  activeCourses: 5,
  totalViews: 12453,
};

export const mockProjects: Project[] = [
  {
    id: '1',
    title: 'Abstract Expressions',
    description: 'A contemporary exploration of emotions through abstract forms and vibrant colors.',
    category: 'Visual Art',
    thumbnail: 'https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=400',
    date: '2024-05-15',
  },
  {
    id: '2',
    title: 'Modern Living Room Redesign',
    description: 'Complete transformation of a traditional space into a modern, functional living area.',
    category: 'Interior Design',
    thumbnail: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=400',
    date: '2024-06-10',
    beforeImage: 'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=400',
    afterImage: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=400',
  },
  {
    id: '3',
    title: 'Therapeutic Art Workshop Series',
    description: 'A 6-week program using art as a medium for emotional healing and self-expression.',
    category: 'Art Therapy',
    thumbnail: 'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=400',
    date: '2024-04-20',
  },
  {
    id: '4',
    title: 'Children\'s Creative Development Program',
    description: 'Educational curriculum designed to foster creativity and artistic skills in young learners.',
    category: 'Art Education',
    thumbnail: 'https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=400',
    date: '2024-05-28',
  },
  {
    id: '5',
    title: 'Minimalist Bedroom Sanctuary',
    description: 'Creating a peaceful retreat with clean lines and natural materials.',
    category: 'Interior Design',
    thumbnail: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=400',
    date: '2024-06-05',
    beforeImage: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=400',
    afterImage: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=400',
  },
  {
    id: '6',
    title: 'Watercolor Landscapes Collection',
    description: 'Series of serene landscape paintings capturing the beauty of nature.',
    category: 'Visual Art',
    thumbnail: 'https://images.unsplash.com/photo-1547891654-e66ed7ebb968?w=400',
    date: '2024-03-12',
  },
];

export const mockCourses: Course[] = [
  {
    id: '1',
    title: 'Introduction to Abstract Painting',
    description: 'Learn the fundamentals of abstract art, exploring color theory, composition, and personal expression through various painting techniques.',
    status: 'Published',
    date: '2024-07-01',
    duration: '8 weeks',
    capacity: 20,
    enrolled: 18,
    image: 'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=400',
  },
  {
    id: '2',
    title: 'Interior Design Fundamentals',
    description: 'Comprehensive course covering space planning, color schemes, furniture selection, and styling principles for residential interiors.',
    status: 'Published',
    date: '2024-07-15',
    duration: '10 weeks',
    capacity: 15,
    enrolled: 12,
    image: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=400',
  },
  {
    id: '3',
    title: 'Art Therapy for Beginners',
    description: 'Explore the healing power of art through guided exercises and therapeutic techniques designed for personal growth and emotional wellness.',
    status: 'Published',
    date: '2024-08-01',
    duration: '6 weeks',
    capacity: 12,
    enrolled: 10,
    image: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400',
  },
  {
    id: '4',
    title: 'Teaching Art to Children',
    description: 'Practical strategies and creative approaches for educators looking to inspire young artists and develop age-appropriate art curricula.',
    status: 'Draft',
    date: '2024-09-01',
    duration: '4 weeks',
    capacity: 25,
    enrolled: 0,
    image: 'https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=400',
  },
  {
    id: '5',
    title: 'Advanced Watercolor Techniques',
    description: 'Master advanced watercolor methods including wet-on-wet, layering, and creating depth in landscape and portrait painting.',
    status: 'Published',
    date: '2024-07-20',
    duration: '6 weeks',
    capacity: 15,
    enrolled: 14,
    image: 'https://images.unsplash.com/photo-1547891654-e66ed7ebb968?w=400',
  },
];

export const mockMessages: Message[] = [
  {
    id: '1',
    senderName: 'Sarah Johnson',
    email: 'sarah.johnson@email.com',
    subject: 'Inquiry about Interior Design Services',
    message: 'Hello Dr. Allam, I came across your portfolio and I\'m very impressed with your interior design work. I\'m looking to redesign my living room and would love to discuss your availability and rates. Could we schedule a consultation?',
    interests: ['Interior Design'],
    date: '2024-06-16',
    status: 'Unread',
  },
  {
    id: '2',
    senderName: 'Michael Chen',
    email: 'mchen@email.com',
    subject: 'Art Therapy Workshop Registration',
    message: 'I\'m interested in joining your upcoming art therapy workshop. Could you please provide more details about the schedule, location, and what materials I need to bring?',
    interests: ['Art Therapy'],
    date: '2024-06-15',
    status: 'Read',
  },
  {
    id: '3',
    senderName: 'Emily Martinez',
    email: 'emily.m@school.edu',
    subject: 'Collaboration on Art Education Program',
    message: 'Dear Dr. Allam, I\'m an art coordinator at Riverside Elementary School. We\'re developing a new art curriculum and would love to collaborate with you on this project. Are you available for a meeting next week?',
    interests: ['Art Education'],
    date: '2024-06-14',
    status: 'Unread',
  },
  {
    id: '4',
    senderName: 'David Thompson',
    email: 'david.t@gmail.com',
    subject: 'Purchase Inquiry - Abstract Expressions',
    message: 'Hi, I saw your "Abstract Expressions" piece and I\'m very interested in purchasing it. Is it still available? What are the dimensions and pricing?',
    interests: ['Visual Art'],
    date: '2024-06-13',
    status: 'Read',
  },
  {
    id: '5',
    senderName: 'Lisa Anderson',
    email: 'lisa.anderson@therapy.org',
    subject: 'Art Therapy Collaboration Opportunity',
    message: 'Hello Dr. Allam, I represent the Community Wellness Center and we\'re looking for an art therapist to lead weekly sessions with our clients. Your credentials and portfolio are exactly what we\'re looking for. Would you be interested in discussing this opportunity?',
    interests: ['Art Therapy'],
    date: '2024-06-12',
    status: 'Unread',
  },
  {
    id: '6',
    senderName: 'Robert Williams',
    email: 'rwilliams@design.com',
    subject: 'Full Home Redesign Project',
    message: 'We have a 3-bedroom home that needs a complete interior redesign. Your modern aesthetic is exactly what we\'re looking for. Can we schedule a consultation to discuss the project scope and timeline?',
    interests: ['Interior Design'],
    date: '2024-06-11',
    status: 'Read',
  },
  {
    id: '7',
    senderName: 'Amanda Foster',
    email: 'afoster@artgallery.com',
    subject: 'Exhibition Invitation',
    message: 'Dear Dr. Allam, The Contemporary Art Gallery is hosting an exhibition featuring emerging artists in visual art and art therapy. We would be honored to feature your work. Please let me know if you\'re interested.',
    interests: ['Visual Art', 'Art Therapy'],
    date: '2024-06-10',
    status: 'Unread',
  },
  {
    id: '8',
    senderName: 'James Parker',
    email: 'j.parker@university.edu',
    subject: 'Guest Lecture Request',
    message: 'Hello, I\'m the head of the Art Education department at City University. Would you be interested in giving a guest lecture on integrating art therapy principles into educational settings?',
    interests: ['Art Education', 'Art Therapy'],
    date: '2024-06-09',
    status: 'Unread',
  },
];

export const mockMedia: MediaItem[] = [
  {
    id: '1',
    url: 'https://images.unsplash.com/photo-1561214115-f2f134cc4912?w=400',
    name: 'hero-background-1.jpg',
    uploadDate: '2024-06-01',
    size: '2.4 MB',
  },
  {
    id: '2',
    url: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=400',
    name: 'studio-workspace.jpg',
    uploadDate: '2024-05-28',
    size: '1.8 MB',
  },
  {
    id: '3',
    url: 'https://images.unsplash.com/photo-1547891654-e66ed7ebb968?w=400',
    name: 'artwork-sample.jpg',
    uploadDate: '2024-05-20',
    size: '3.1 MB',
  },
  {
    id: '4',
    url: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400',
    name: 'therapy-session.jpg',
    uploadDate: '2024-05-15',
    size: '2.2 MB',
  },
  {
    id: '5',
    url: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=400',
    name: 'interior-design-showcase.jpg',
    uploadDate: '2024-05-10',
    size: '2.7 MB',
  },
  {
    id: '6',
    url: 'https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=400',
    name: 'children-art-class.jpg',
    uploadDate: '2024-05-05',
    size: '1.9 MB',
  },
];

export const mockRecentActivity: RecentActivity[] = [
  {
    id: '1',
    type: 'message',
    title: 'New message from Sarah Johnson',
    description: 'Inquiry about Interior Design Services',
    date: '2024-06-16',
  },
  {
    id: '2',
    type: 'message',
    title: 'New message from Emily Martinez',
    description: 'Collaboration on Art Education Program',
    date: '2024-06-14',
  },
  {
    id: '3',
    type: 'course',
    title: 'New enrollment in "Introduction to Abstract Painting"',
    description: 'Course capacity: 18/20',
    date: '2024-06-13',
  },
  {
    id: '4',
    type: 'message',
    title: 'New message from Lisa Anderson',
    description: 'Art Therapy Collaboration Opportunity',
    date: '2024-06-12',
  },
  {
    id: '5',
    type: 'course',
    title: 'New enrollment in "Advanced Watercolor Techniques"',
    description: 'Course capacity: 14/15',
    date: '2024-06-11',
  },
];
